<a href="https://colab.research.google.com/github/HemanthKumarA12/demo/blob/master/handlingNA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np


In [0]:
import pandas as pd

In [0]:
X= np.array([[1.1,11.1],
             [2.3,22.2],
             [3.3,33.3],
             [4.4,44.4],
             [np.nan, 55]
             
             
             ])

In [7]:
X

array([[ 1.1, 11.1],
       [ 2.3, 22.2],
       [ 3.3, 33.3],
       [ 4.4, 44.4],
       [ nan, 55. ]])

ARRANGE FUNCTION TO CREATE TWO DIMENSIONAL ARRAY

In [0]:
a = np.arange(12).reshape(3, 4)

In [9]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
X=np.delete(X,(4), axis=0)

In [11]:
print(X)

[[ 1.1 11.1]
 [ 2.3 22.2]
 [ 3.3 33.3]
 [ 4.4 44.4]]


In [0]:
X=np.delete(X,(1),axis=1)

In [13]:
X

array([[1.1],
       [2.3],
       [3.3],
       [4.4]])

**CREATE A DATAFRAME PASSING NUMPY ARRAY**

In [0]:
data= np.arange(10).reshape(5,2)

In [15]:
print(data)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [0]:
df=pd.DataFrame(data=data,columns=['score1','score2'])

In [17]:
df

score1  score2
0       0       1
1       2       3
2       4       5
3       6       7
4       8       9

In [0]:
df= pd.DataFrame([[np.nan, 2, np.nan,0],
                 [3,4,np.nan,1],
                 [np.nan,np.nan,np.nan,5],
                 [np.nan, 3, np.nan,4]],
                 columns=list('ABCD'))
                 
        

In [21]:
df

A    B   C  D
0  NaN  2.0 NaN  0
1  3.0  4.0 NaN  1
2  NaN  NaN NaN  5
3  NaN  3.0 NaN  4

**REPLACE NAN WITH ZERO**

In [22]:
 df.fillna(0)

A    B    C  D
0  0.0  2.0  0.0  0
1  3.0  4.0  0.0  1
2  0.0  0.0  0.0  5
3  0.0  3.0  0.0  4

In [0]:
values={'A':0,'B':1,'C':2,'D':3}

In [24]:
df.fillna(value=values)

A    B    C  D
0  0.0  2.0  2.0  0
1  3.0  4.0  2.0  1
2  0.0  1.0  2.0  5
3  0.0  3.0  2.0  4

In [25]:
df.fillna(value=values, limit=1)

A    B    C  D
0  0.0  2.0  2.0  0
1  3.0  4.0  NaN  1
2  NaN  1.0  NaN  5
3  NaN  3.0  NaN  4